### PR TITLE
Scala 2.13.0-M5

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by SethTisue** [comment]
any maintainers around...?

**Comment by marklister** [comment]
Yeah, battling DRC internet, You need this published asap I guess?

**Comment by SethTisue** [comment]
well there's merging, and there's publishing

for me a merge is just a would-be-nice to get base64 green in the Scala community build

as for publishing, 2.13.0-RC1 is coming out very soon anyway (hopefully next week)

**Comment by marklister** [comment]
Ok, I've fixed up my build and generated keys etc and hopefully this merge gets you where you need to be.  I'll republish when 2.13.0 is out or if someone needs me to before then.

**Pull request merged**
